repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        exclude: ^(/migrations/|tests/)
        args: ['--line-length=120']
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: ^(/migrations/|tests/)
        args: [--max-line-length=120, --extend-ignore=E501]
